CREATE TABLE feedback (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    audio_file_path TEXT NOT NULL,
    transcript TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);